<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cards', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('user_id');
            $table->string('design');
            $table->string('profile_photo');
            $table->string('color');
            $table->string('logo');
            $table->string('badge');
            $table->string('card_name');
            $table->string('prefix');
            $table->string('first_name');
            $table->string('middle_name');
            $table->string('last_name');
            $table->string('suffix');
            $table->string('accreditation');
            $table->string('preferred_name');
            $table->string('maiden_name');
            $table->string('pronouns');
            $table->string('title');
            $table->string('department');
            $table->string('company');
            $table->text('headline');
            $table->string('website_text');
            $table->string('website_link');
            $table->string('link_text');
            $table->string('link_link');
            $table->string('instagram_text');
            $table->string('instagram_link');
            $table->string('applemusic_link');
            $table->string('applemusic_text');
            $table->string('behance_link');
            $table->string('behance_text');
            $table->string('bookings_link');
            $table->string('bookings_text');
            $table->string('brightcove_link');
            $table->string('brightcove_text');
            $table->string('calendly_link');
            $table->string('calendly_text');
            $table->string('cashapp_link');
            $table->string('cashapp_text');
            $table->string('discord_link');
            $table->string('discord_text');
            $table->string('dribbble_link');
            $table->string('dribbble_text');
            $table->string('facebook_link');
            $table->string('facebook_text');
            $table->string('github_link');
            $table->string('github_text');
            $table->string('line_link');
            $table->string('line_text');
            $table->string('linkedin_link');
            $table->string('linkedin_text');
            $table->string('meet_link');
            $table->string('meet_text');
            $table->string('nintendo_link');
            $table->string('nintendo_text');
            $table->string('patreon_link');
            $table->string('patreon_text');
            $table->string('paypal_link');
            $table->string('paypal_text');
            $table->string('pinterest_link');
            $table->string('pinterest_text');
            $table->string('psn_link');
            $table->string('psn_text');
            $table->string('signal_link');
            $table->string('signal_text');
            $table->string('skype_link');
            $table->string('skype_text');
            $table->string('snapchat_link');
            $table->string('snapchat_text');
            $table->string('soundcloud_link');
            $table->string('soundcloud_text');
            $table->string('spotify_link');
            $table->string('spotify_text');
            $table->string('teams_link');
            $table->string('teams_text');
            $table->string('telegram_link');
            $table->string('telegram_text');
            $table->string('tiktok_link');
            $table->string('tiktok_text');
            $table->string('twitch_link');
            $table->string('twitch_text');
            $table->string('venmo_link');
            $table->string('venmo_text');
            $table->string('vimeo_link');
            $table->string('vimeo_text');
            $table->string('webex_link');
            $table->string('webex_text');
            $table->string('wechat_link');
            $table->string('wechat_text');
            $table->string('whatsapp_link');
            $table->string('whatsapp_text');
            $table->string('x.com_link');
            $table->string('x.com_text');
            $table->string('xbox_link');
            $table->string('xbox_text');
            $table->string('xing_link');
            $table->string('xing_text');
            $table->string('yelp_link');
            $table->string('yelp_text');
            $table->string('youtube_link');
            $table->string('youtube_text');
            $table->string('zelle_link');
            $table->string('zelle_text');
            $table->string('zoom_link');
            $table->string('zoom_text');
            $table->string('address');
            $table->string('address_text');
            $table->string('date');
            $table->string('date_text');
            $table->string('email');
            $table->string('email_text');
            $table->text('note');
            $table->string('pdf');
            $table->string('pdf_text');
            $table->string('phone');
            $table->string('phone_text');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cards');
    }
};
